<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Modelo\Modelo.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.Reporting" Version="2.1.0" />
    <PackageReference Include="QuestPDF" Version="2025.5.1" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Origen\dsreport.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>dsreport.xsd</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Origen\dsreport.xsd">
      <Generator>MSDataSetGenerator</Generator>
      <LastGenOutput>dsreport.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="logo.png" />
  </ItemGroup>

</Project>
