name: Deploy WASM Frontend to Amazon S3 + CloudFront

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-2

jobs:
  deploy:
    name: Build & Deploy WASM Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Publish Blazor WebAssembly Client
        run: |
          dotnet publish C.Presentación/BsOperaciones.Wasm/BsOperaciones.Wasm.csproj \
            -c Release \
            -o release

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Sync static files to AWS S3
        run: |
          aws s3 sync release/wwwroot/ s3://${{ secrets.AWS_S3_BUCKET_NAME }} --delete

      - name: Invalidate CloudFront Cache
        continue-on-error: true
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"
